[versions]
agp = "8.2.1"

nav = "2.7.6"

appcompat = "1.6.1"
material = "1.11.0"

treeview = "1.1.4"
flexbox = "3.0.0"

gson = "2.10.1"
mmkv = "1.3.2"
shizuku = "13.1.5"

kotlin = "1.9.22"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

nav-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "nav" }
nav-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "nav" }

treeview = { group = "io.github.amrdeveloper", name = "treeview", version.ref = "treeview" }
flexbox = { group = "com.google.android.flexbox", name = "flexbox", version.ref = "flexbox" }

gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
mmkv = { group = "com.tencent", name = "mmkv", version.ref = "mmkv" }

shizuku-api = { group = "dev.rikka.shizuku", name = "api", version.ref = "shizuku"}
shizuku-provider = { group = "dev.rikka.shizuku", name = "provider", version.ref = "shizuku"}

kotlin-bom = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlin" }

[plugins]
application = { id = "com.android.application", version.ref = "agp" }
nav-safeargs = { id = "androidx.navigation.safeargs", version.ref = "nav" }

[bundles]

